"""Bake out/summary.json into a deployable Cloudflare Worker that serves it with
CORS headers. Run after refresh.py:

  python3 refresh.py 30d
  python3 build_worker.py
  # then deploy worker/speed-to-lead-data.js to Cloudflare

The Worker returns the high-level summary (a few KB, no PII) at any path with
`Access-Control-Allow-Origin: *`, so the Framer component can fetch it.
"""
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(ROOT, "out", "summary.json")))

worker = (
    "// AUTO-GENERATED by build_worker.py — do not edit by hand.\n"
    "// Serves the pre-computed Speed-to-Lead dataset with CORS.\n"
    "// Deploy to Cloudflare Workers; point the Framer component's Data URL here.\n"
    "const DATA = " + json.dumps(data, separators=(",", ":")) + ";\n\n"
    "export default {\n"
    "  async fetch() {\n"
    "    return new Response(JSON.stringify(DATA), {\n"
    "      headers: {\n"
    '        "content-type": "application/json",\n'
    '        "access-control-allow-origin": "*",\n'
    '        "cache-control": "public, max-age=300",\n'
    "      },\n"
    "    });\n"
    "  },\n"
    "};\n"
)

os.makedirs(os.path.join(ROOT, "worker"), exist_ok=True)
out = os.path.join(ROOT, "worker", "speed-to-lead-data.js")
with open(out, "w") as fh:
    fh.write(worker)
print("wrote", out, f"({len(worker)//1024} KB, {data['meta']['lead_count']} leads)")
